# Commands used to enable/disable
# services for WURB_2026 and WIRC_2026.
#
# Installation:
#
# cp /home/wurb/wurb_2026/raspberrypi_files/bash_aliases /home/wurb/.bash_aliases
# chmod 755 /home/wurb/.bash_aliases
# source /home/wurb/.bash_aliases
#

function wurb-on {
    sudo systemctl enable wurb_2026.service
    sudo systemctl start wurb_2026.service
}
function wurb-off {
    sudo systemctl disable wurb_2026.service
    sudo systemctl stop wurb_2026.service
}
function wurb-status {
    sudo systemctl status wurb_2026.service
}

function wirc-on {
    sudo systemctl enable wirc_2026.service
    sudo systemctl start wirc_2026.service
}
function wirc-off {
    sudo systemctl disable wirc_2026.service
    sudo systemctl stop wirc_2026.service
}
function wirc-status {
    sudo systemctl status wirc_2026.service
}
