
function wurb-on {
    sudo systemctl enable wurb_2026.service
    sudo systemctl start wurb_2026.service
}
function wurb-off {
    sudo systemctl disable wurb_2026.service
    sudo systemctl stop wurb_2026.service
}
function wurb-status {
    sudo systemctl status wurb_2026.service
}

function wirc-on {
    sudo systemctl enable wirc_2026.service
    sudo systemctl start wirc_2026.service
}
function wirc-off {
    sudo systemctl disable wirc_2026.service
    sudo systemctl stop wirc_2026.service
}
function wirc-status {
    sudo systemctl status wirc_2026.service
}
